FROM debian:latest AS builder
#WORKDIR /tmp/
RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* \
	&& localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8

RUN apt-get update && apt-get install -y \
    git \
    gcc \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/klvlsk/Shell.git \
    && cd Shell  \
    && gcc -static -o out app/main.c

WORKDIR /Linux_shell/
#CMD ["gcc", "-static", "-o", "out", "app/main.c"]
#CMD ["/bin/ls"]
#CMD ["/bin/echo", " "]
#CMD ["/bin/ls", "/Shell"]
#CMD ["/bin/yes"]

FROM scratch 
WORKDIR /
COPY --from=builder /Shell/out .
ENTRYPOINT ["./out"]
